name: Stock Monitor

on:
  schedule:
    # 台灣時間 22:00
    # GitHub Actions 使用 UTC，所以 22:00 - 8 小時 = 14:00 UTC
    - cron: '0 14 * * 1-5'

  workflow_dispatch:

jobs:
  run-stock-bot:

    runs-on: ubuntu-latest

    env:
      LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        run: python main.py
