name: Stock Monitor

on:
  schedule:
    # 台灣時間約 21:00，避免 GitHub Actions 延遲到太晚
    - cron: '0 13 * * 1-5'

  workflow_dispatch:
jobs:
  run-stock-bot:

    runs-on: ubuntu-latest

    env:
      LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        run: python main.py
